name: Fid type on files

on:
  push:
    branches: [ develop ]

jobs:
  test-memory-2026:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create empty file and loop on it to find type
        run: |
          for f in $(find . -type f -name "*.*"); do
            cp "$f" empty_file
            file empty_file
          done

  build-memory-2026:
    runs-on: ubuntu-latest
    needs: test-memory-2026   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t amekishibe/memory-2026 .

  deploy-memory-2026:
    runs-on: ubuntu-latest
    needs: build-memory-2026
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push image on docker hub
        run: |
          docker login -u amekishibe
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push amekishibe/memory-2026